// DO NOT EDIT: Code generated by matcha from fail.matcha

import gleam/string_tree.{type StringTree}

pub fn render_builder() -> StringTree {
  let builder = string_tree.from_string("")
  let builder =
    string_tree.append(
      builder,
      "<h1>Bad request</h1>

",
    )

  builder
}

pub fn render() -> String {
  string_tree.to_string(render_builder())
}
