// DO NOT EDIT: Code generated by matcha from form.matcha

import gleam/string_builder.{StringBuilder}
import gleam/list



pub fn render_builder() -> StringBuilder {
    let builder = string_builder.from_string("")
    let builder = string_builder.append(builder, "<h1>Is it up?</h1>
")

    builder
}

pub fn render() -> String {
    string_builder.to_string(render_builder())
}
