// DO NOT EDIT: Code generated by matcha from not_found.matcha

import gleam/string_builder.{StringBuilder}



pub fn render_builder() -> StringBuilder {
    let builder = string_builder.from_string("")
    let builder = string_builder.append(builder, "<h1>You're lost!</h1>
")

    builder
}

pub fn render() -> String {
    string_builder.to_string(render_builder())
}
